### ISSUE TITLE
issue when trying to publish to pulsar broker

### ISSUE THREAD

**Issue by otmanel31** [streamlio/nifi-pulsar-bundle#18]
Hi,
I face an issue when trying to publish on pulsar with following error:

> 2019-08-29 09:15:26,749 ERROR [Timer-Driven Process Thread-5] o.a.n.p.pulsar.pubsub.PublishPulsar PublishPulsar[id=de260534-016c-1000-5f3d-db6103ca25d8] Unable to publish message to Pulsar broker pulsar://localhost:6650: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:413)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:215)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:78)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:55)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:52)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.send(PublishPulsar.java:115)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.onTrigger(PublishPulsar.java:83)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1162)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:205)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.common.api.Commands.serializeCommandSendWithSize(Commands.java:948)
	at org.apache.pulsar.common.api.Commands.newSend(Commands.java:315)
	at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:449)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:376)
	... 17 common frames omitted

May be there is a dependency issue or version mismatch ?

**Comment by david-streamlio** [comment]
@otmanel31 I have updated the dependencies to use the unshaded pulsar-client jar, which resolved a similar [issue](https://github.com/apache/pulsar/pull/3000).  To confirm the availability of the `com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum` method, I added the following to a processor`s code and complied successfully.

`ByteBuf buf = new EmptyByteBuf(ByteBufAllocator.DEFAULT);
Crc32cIntChecksum.computeChecksum(buf);`

**Comment by otmanel31** [comment]
Hi, 
To begin thanks for quick response.
I build nifi pulsar bundle again and i'm currently able to publish to pulsar broker over Nifi flow.
We can close this issue now.
Thank you. :)

**Comment by david-streamlio** [comment]
Awesome.  Thanks for the quick feedback
